"""View test steps for user-requirement scenarios"""
import sys
from pathlib import Path

# Add backend to path
backend_path = Path(__file__).parent.parent.parent
sys.path.insert(0, str(backend_path))

from app.db.session import SessionLocal
from app.models.test_case import TestCase
import json

def view_user_requirement_steps(user_requirement_keywords=None):
    """
    View test steps for scenarios matching user requirements.
    
    Args:
        user_requirement_keywords: List of keywords to search for in test case titles
                                   Default: ["5g寬頻數據無限任用", "purchase flow"]
    """
    if user_requirement_keywords is None:
        user_requirement_keywords = ["5g寬頻數據無限任用", "purchase flow", "立即登記"]
    
    db = SessionLocal()
    try:
        # Query all test cases
        test_cases = db.query(TestCase).order_by(TestCase.id.desc()).limit(50).all()
        
        print("="*80)
        print("Test Cases Matching User Requirement Keywords:")
        print(f"  Keywords: {', '.join(user_requirement_keywords)}")
        print("="*80)
        
        matching_cases = []
        for tc in test_cases:
            title_lower = tc.title.lower() if tc.title else ""
            # Check if title contains any keyword
            if any(keyword.lower() in title_lower for keyword in user_requirement_keywords):
                matching_cases.append(tc)
        
        if not matching_cases:
            print("\n❌ No test cases found matching the keywords.")
            print("   Try running the test first to generate test cases.")
            return
        
        print(f"\n✅ Found {len(matching_cases)} matching test case(s):\n")
        
        for idx, tc in enumerate(matching_cases, 1):
            print(f"{'='*80}")
            print(f"Test Case #{idx}")
            print(f"{'='*80}")
            print(f"ID: {tc.id}")
            print(f"Title: {tc.title}")
            
            # Get scenario ID from metadata
            scenario_id = "N/A"
            if tc.test_metadata:
                if isinstance(tc.test_metadata, dict):
                    scenario_id = tc.test_metadata.get('scenario_id', 'N/A')
                else:
                    try:
                        metadata = json.loads(tc.test_metadata)
                        scenario_id = metadata.get('scenario_id', 'N/A')
                    except:
                        pass
            
            print(f"Scenario ID: {scenario_id}")
            print(f"Priority: {tc.priority.value if hasattr(tc.priority, 'value') else tc.priority}")
            print(f"Test Type: {tc.test_type.value if hasattr(tc.test_type, 'value') else tc.test_type}")
            
            # Show steps
            print(f"\n📋 Test Steps ({len(tc.steps) if isinstance(tc.steps, list) else 0}):")
            print("-"*80)
            
            if isinstance(tc.steps, list):
                for step_idx, step in enumerate(tc.steps, 1):
                    print(f"{step_idx:2d}. {step}")
            elif isinstance(tc.steps, str):
                print(f"⚠️  Steps stored as string (should be list):")
                print(f"    {tc.steps[:200]}...")
            else:
                print(f"❌ Steps type: {type(tc.steps)}")
                print(f"    {tc.steps}")
            
            # Show expected result
            if tc.expected_result:
                print(f"\n✅ Expected Result:")
                print(f"   {tc.expected_result[:200]}{'...' if len(tc.expected_result) > 200 else ''}")
            
            # Show metadata
            if tc.test_metadata:
                print(f"\n📊 Metadata:")
                if isinstance(tc.test_metadata, dict):
                    metadata = tc.test_metadata
                else:
                    try:
                        metadata = json.loads(tc.test_metadata)
                    except:
                        metadata = {}
                
                if metadata:
                    print(f"   - Generation ID: {metadata.get('generation_id', 'N/A')}")
                    print(f"   - RPN: {metadata.get('rpn', 'N/A')}")
                    print(f"   - Scenario Type: {metadata.get('scenario_type', 'N/A')}")
                    print(f"   - Generated By: {metadata.get('generated_by', 'N/A')}")
            
            print()  # Empty line between test cases
        
        print(f"{'='*80}")
        print(f"Total: {len(matching_cases)} test case(s) found")
        print(f"{'='*80}")
        
    finally:
        db.close()

if __name__ == "__main__":
    import argparse
    
    parser = argparse.ArgumentParser(description="View test steps for user-requirement scenarios")
    parser.add_argument(
        "--keywords",
        nargs="+",
        default=["5g寬頻數據無限任用", "purchase flow", "立即登記"],
        help="Keywords to search for in test case titles"
    )
    
    args = parser.parse_args()
    view_user_requirement_steps(args.keywords)

